services:
  - type: web
    name: elroi-fast-food
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: COOKIE_SECURE
        value: "0"
      - key: PORT
        value: "10000"
